num=input("Enter your number: ")
count=0
index=0
for i in range(len(num)):
    if(num[i]=='-'):
        count+=1
        index=i

if(count<=0):
    if(num=="zero"):
        print("0")
    elif(num=="one"):
        print("1")
    elif(num=="two"):
        print("2")
    elif(num=="three"):
        print("3")
    elif(num=="four"):
        print("4")
    elif(num=="five"):
        print("5")
    elif(num=="six"):
        print("6")
    elif(num=="seven"):
        print("7")
    elif(num=="eight"):
        print("8")
    elif(num=="nine"):
        print("9")
    elif(num=="eleven"):
        print("11")
    elif(num=="twelve"):
        print("12")
    elif(num=="thirteen"):
        print("13")
    elif(num=="fourteen"):
        print("14")
    elif(num=="fifteen"):
        print("15")
    elif(num=="sixteen"):
        print("16")
    elif(num=="seventeen"):
        print("17")
    elif(num=="eighteen"):
        print("18")
    elif(num=="nineteen"):
        print("19")
    elif(num=="twenty"):
        print("20")
    elif(num=="thirty"):
        print("30")
    elif(num=="forty"):
        print("40")
    elif(num=="fifty"):
        print("50")
    elif(num=="sixty"):
        print("60")
    elif(num=="seventy"):
        print("70")
    elif(num=="eighty"):
        print("80")
    elif(num=="ninety"):
        print("90")
else:
    units=num[index+1:len(num)]
    tens=num[0:index]
    if(tens=="twenty"):
        print("2",end="")
    elif(tens=="thirty"):
        print("3",end="")
    elif(tens=="forty"):
        print("4",end="")
    elif(tens=="fifty"):
        print("5",end="")
    elif(tens=="sixty"):
        print("6",end="")
    elif(tens=="seventy"):
        print("7",end="")
    elif(tens=="eighty"):
        print("8",end="")
    elif(tens=="ninety"):
        print("9",end="")

    if(units=="one"):
        print("1")
    elif(units=="two"):
        print("2")
    elif(units=="three"):
        print("3")
    elif(units=="four"):
        print("4")
    elif(units=="five"):
        print("5")
    elif(units=="six"):
        print("6")
    elif(units=="seven"):
        print("7")
    elif(units=="eight"):
        print("8")
    elif(units=="nine"):
        print("9")
        